from django.utils.translation import gettext_lazy as _

VARIABLES = [
    ('pi_tag', _('PI Tag')),
    ('pi_format', _('PI Format')),
    ('invoice_tag', _('Invoice Tag')),
    ('invoice_format', _('Invoice Format')),
]

FORMAT = [
    ('{py}-{fy}/{tag}/{num:04d}', _('23-24/tag/0001')),
    ('{py}-{fy}/{tag}-{num:04d}', _('23-24/tag-0001')),
    ('{tag}/{py}-{fy}/{num:04d}', _('tag/23-24/0001')),
    ('{tag}-{num:04d}/{py}-{fy}', _('tag-0001/23-24')),
]

STATUS_CHOICES = [
    ('open', _('OPEN')),
    ('closed', _('CLOSED')),
    ('lost', _('LOST')),
]

SUBSCRIPTION_MODE = [
    ('email', _('EMAIL')),
    ('online', _('ONLINE')),
]

PAYMENT_TERM = [
    ('advance', _('ADVANCED')),
    ('credit', _('CREDIT')),
]

CATEGORY = [
    ('offline', _('BE USA TRADE PUBLICATIONS')),
    ('online', _('BE USA TRADE SUBSCRIPTION'))
]

REPORT_TYPE = [
    ('export', _('Outbound Insight')),
    ('import', _('Inbound Insight')),
    ('online', _('Subscription')),
    ('domestic', _('Market Research')),
]

REPORTS = [
    ('export', _('EXPORT')),
    ('import', _('IMPORT')),
]

REPORT_FORMAT =[
    ('monthly', _('Monthly')),
    ('weekly', _('weekly')),
    ('10 days', _('10 Days')),
    ('sez', _('SEZ')),
    ('sez(weekly)', _('SEZ (Weekly)')),
    ('incoterm', _('Incoterm')),
]


ORDER_STATUS = [
    ('pending', _('Pending')),
    ('processing', _('Processing')),
    ('complete', _('Complete')),
]

PAYMENT_STATUS = [
    ('full', _('Full')),
    ('credit', _('Credit')),
    ('partial', _('Partial')),
]


# COUNTRY_CHOICE =[
#     ('IN', _('INDIA')),
#     ('US', _('UNITED STATES')),
# ]



STATE_CHOICE = [
    (1, 'JAMMU AND KASHMIR'),
    (2, 'HIMACHAL PRADESH'),
    (3, 'PUNJAB'),
    (4, 'CHANDIGARH'),
    (5, 'UTTARAKHAND'),
    (6, 'HARYANA'),
    (7, 'DELHI'),
    (8, 'RAJASTHAN'),
    (9, 'UTTAR PRADESH'),
    (10, 'BIHAR'),
    (11, 'SIKKIM'),
    (12, 'ARUNACHAL PRADESH'),
    (13, 'NAGALAND'),
    (14, 'MANIPUR'),
    (15, 'MIZORAM'),
    (16, 'TRIPURA'),
    (17, 'MEGHALAYA'),
    (18, 'ASSAM'),
    (19, 'WEST BENGAL'),
    (20, 'JHARKHAND'),
    (21, 'ODISHA'),
    (22, 'CHATTISGARH'),
    (23, 'MADHYA PRADESH'),
    (24, 'GUJARAT'),
    (26, 'DADRA AND NAGAR HAVELI AND DAMAN AND DIU (NEWLY MERGED UT)'),
    (27, 'MAHARASHTRA'),
    (28, 'ANDHRA PRADESH(BEFORE DIVISION)'),
    (29, 'KARNATAKA'),
    (30, 'GOA'),
    (31, 'LAKSHADWEEP'),
    (32, 'KERALA'),
    (33, 'TAMIL NADU'),
    (34, 'PUDUCHERRY'),
    (35, 'ANDAMAN AND NICOBAR ISLANDS'),
    (36, 'TELANGANA'),
    (37, 'ANDHRA PRADESH (NEWLY ADDED)'),
    (38, 'LADAKH (NEWLY ADDED)'),
    (97, 'OTHER TERRITORY'),
    (99, 'CENTRE JURISDICTION')
    ]

COUNTRY_CHOICE = [
    ("AF", "Afghanistan"),
    ("AX", "\u00c5land Islands"),
    ("AL", "Albania"),
    ("DZ", "Algeria"),
    ("AS", "American Samoa"),
    ("AD", "Andorra"),
    ("AO", "Angola"),
    ("AI", "Anguilla"),
    ("AQ", "Antarctica"),
    ("AG", "Antigua & Barbuda"),
    ("AR", "Argentina"),
    ("AM", "Armenia"),
    ("AW", "Aruba"),
    ("AU", "Australia"),
    ("AT", "Austria"),
    ("AZ", "Azerbaijan"),
    ("BS", "Bahamas"),
    ("BH", "Bahrain"),
    ("BD", "Bangladesh"),
    ("BB", "Barbados"),
    ("BY", "Belarus"),
    ("BE", "Belgium"),
    ("BZ", "Belize"),
    ("BJ", "Benin"),
    ("BM", "Bermuda"),
    ("BT", "Bhutan"),
    ("BO", "Bolivia"),
    ("BA", "Bosnia & Herzegovina"),
    ("BW", "Botswana"),
    ("BV", "Bouvet Island"),
    ("BR", "Brazil"),
    ("IO", "British Indian Ocean Territory"),
    ("VG", "British Virgin Islands"),
    ("BN", "Brunei"),
    ("BG", "Bulgaria"),
    ("BF", "Burkina Faso"),
    ("BI", "Burundi"),
    ("KH", "Cambodia"),
    ("CM", "Cameroon"),
    ("CA", "Canada"),
    ("CV", "Cape Verde"),
    ("BQ", "Caribbean Netherlands"),
    ("KY", "Cayman Islands"),
    ("CF", "Central African Republic"),
    ("TD", "Chad"),
    ("CL", "Chile"),
    ("CN", "China"),
    ("CX", "Christmas Island"),
    ("CC", "Cocos (Keeling) Islands"),
    ("CO", "Colombia"),
    ("KM", "Comoros"),
    ("CG", "Congo - Brazzaville"),
    ("CD", "Congo - Kinshasa"),
    ("CK", "Cook Islands"),
    ("CR", "Costa Rica"),
    ("CI", "C\u00f4te d\u2019Ivoire"),
    ("HR", "Croatia"),
    ("CU", "Cuba"),
    ("CW", "Cura\u00e7ao"),
    ("CY", "Cyprus"),
    ("CZ", "Czechia"),
    ("DK", "Denmark"),
    ("DJ", "Djibouti"),
    ("DM", "Dominica"),
    ("DO", "Dominican Republic"),
    ("EC", "Ecuador"),
    ("EG", "Egypt"),
    ("SV", "El Salvador"),
    ("GQ", "Equatorial Guinea"),
    ("ER", "Eritrea"),
    ("EE", "Estonia"),
    ("SZ", "Eswatini"),
    ("ET", "Ethiopia"),
    ("FK", "Falkland Islands"),
    ("FO", "Faroe Islands"),
    ("FJ", "Fiji"),
    ("FI", "Finland"),
    ("FR", "France"),
    ("GF", "French Guiana"),
    ("PF", "French Polynesia"),
    ("TF", "French Southern Territories"),
    ("GA", "Gabon"),
    ("GM", "Gambia"),
    ("GE", "Georgia"),
    ("DE", "Germany"),
    ("GH", "Ghana"),
    ("GI", "Gibraltar"),
    ("GR", "Greece"),
    ("GL", "Greenland"),
    ("GD", "Grenada"),
    ("GP", "Guadeloupe"),
    ("GU", "Guam"),
    ("GT", "Guatemala"),
    ("GG", "Guernsey"),
    ("GN", "Guinea"),
    ("GW", "Guinea-Bissau"),
    ("GY", "Guyana"),
    ("HT", "Haiti"),
    ("HM", "Heard & McDonald Islands"),
    ("HN", "Honduras"),
    ("HK", "Hong Kong SAR China"),
    ("HU", "Hungary"),
    ("IS", "Iceland"),
    ("IN", "India"),
    ("ID", "Indonesia"),
    ("IR", "Iran"),
    ("IQ", "Iraq"),
    ("IE", "Ireland"),
    ("IM", "Isle of Man"),
    ("IL", "Israel"),
    ("IT", "Italy"),
    ("JM", "Jamaica"),
    ("JP", "Japan"),
    ("JE", "Jersey"),
    ("JO", "Jordan"),
    ("KZ", "Kazakhstan"),
    ("KE", "Kenya"),
    ("KI", "Kiribati"),
    ("KW", "Kuwait"),
    ("KG", "Kyrgyzstan"),
    ("LA", "Laos"),
    ("LV", "Latvia"),
    ("LB", "Lebanon"),
    ("LS", "Lesotho"),
    ("LR", "Liberia"),
    ("LY", "Libya"),
    ("LI", "Liechtenstein"),
    ("LT", "Lithuania"),
    ("LU", "Luxembourg"),
    ("MO", "Macao SAR China"),
    ("MG", "Madagascar"),
    ("MW", "Malawi"),
    ("MY", "Malaysia"),
    ("MV", "Maldives"),
    ("ML", "Mali"),
    ("MT", "Malta"),
    ("MH", "Marshall Islands"),
    ("MQ", "Martinique"),
    ("MR", "Mauritania"),
    ("MU", "Mauritius"),
    ("YT", "Mayotte"),
    ("MX", "Mexico"),
    ("FM", "Micronesia"),
    ("MD", "Moldova"),
    ("MC", "Monaco"),
    ("MN", "Mongolia"),
    ("ME", "Montenegro"),
    ("MS", "Montserrat"),
    ("MA", "Morocco"),
    ("MZ", "Mozambique"),
    ("MM", "Myanmar (Burma)"),
    ("NA", "Namibia"),
    ("NR", "Nauru"),
    ("NP", "Nepal"),
    ("NL", "Netherlands"),
    ("NC", "New Caledonia"),
    ("NZ", "New Zealand"),
    ("NI", "Nicaragua"),
    ("NE", "Niger"),
    ("NG", "Nigeria"),
    ("NU", "Niue"),
    ("NF", "Norfolk Island"),
    ("KP", "North Korea"),
    ("MK", "North Macedonia"),
    ("MP", "Northern Mariana Islands"),
    ("NO", "Norway"),
    ("OM", "Oman"),
    ("PK", "Pakistan"),
    ("PW", "Palau"),
    ("PS", "Palestinian Territories"),
    ("PA", "Panama"),
    ("PG", "Papua New Guinea"),
    ("PY", "Paraguay"),
    ("PE", "Peru"),
    ("PH", "Philippines"),
    ("PN", "Pitcairn Islands"),
    ("PL", "Poland"),
    ("PT", "Portugal"),
    ("PR", "Puerto Rico"),
    ("QA", "Qatar"),
    ("RE", "R\u00e9union"),
    ("RO", "Romania"),
    ("RU", "Russia"),
    ("RW", "Rwanda"),
    ("WS", "Samoa"),
    ("SM", "San Marino"),
    ("ST", "S\u00e3o Tom\u00e9 & Pr\u00edncipe"),
    ("SA", "Saudi Arabia"),
    ("SN", "Senegal"),
    ("RS", "Serbia"),
    ("SC", "Seychelles"),
    ("SL", "Sierra Leone"),
    ("SG", "Singapore"),
    ("SX", "Sint Maarten"),
    ("SK", "Slovakia"),
    ("SI", "Slovenia"),
    ("SB", "Solomon Islands"),
    ("SO", "Somalia"),
    ("ZA", "South Africa"),
    ("GS", "South Georgia & South Sandwich Islands"),
    ("KR", "South Korea"),
    ("SS", "South Sudan"),
    ("ES", "Spain"),
    ("LK", "Sri Lanka"),
    ("BL", "St. Barth\u00e9lemy"),
    ("SH", "St. Helena"),
    ("KN", "St. Kitts & Nevis"),
    ("LC", "St. Lucia"),
    ("MF", "St. Martin"),
    ("PM", "St. Pierre & Miquelon"),
    ("VC", "St. Vincent & Grenadines"),
    ("SD", "Sudan"),
    ("SR", "Suriname"),
    ("SJ", "Svalbard & Jan Mayen"),
    ("SE", "Sweden"),
    ("CH", "Switzerland"),
    ("SY", "Syria"),
    ("TW", "Taiwan"),
    ("TJ", "Tajikistan"),
    ("TZ", "Tanzania"),
    ("TH", "Thailand"),
    ("TL", "Timor-Leste"),
    ("TG", "Togo"),
    ("TK", "Tokelau"),
    ("TO", "Tonga"),
    ("TT", "Trinidad & Tobago"),
    ("TN", "Tunisia"),
    ("TR", "Turkey"),
    ("TM", "Turkmenistan"),
    ("TC", "Turks & Caicos Islands"),
    ("TV", "Tuvalu"),
    ("UM", "U.S. Outlying Islands"),
    ("VI", "U.S. Virgin Islands"),
    ("UG", "Uganda"),
    ("UA", "Ukraine"),
    ("AE", "United Arab Emirates"),
    ("GB", "United Kingdom"),
    ("US", "United States"),
    ("UY", "Uruguay"),
    ("UZ", "Uzbekistan"),
    ("VU", "Vanuatu"),
    ("VA", "Vatican City"),
    ("VE", "Venezuela"),
    ("VN", "Vietnam"),
    ("WF", "Wallis & Futuna"),
    ("EH", "Western Sahara"),
    ("YE", "Yemen"),
    ("ZM", "Zambia"),
    ("ZW", "Zimbabwe")
    ]