# Generated by Django 5.0.9 on 2024-11-21 17:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('account', 'Account'), ('sales', 'Sales'), ('production', 'Production')], default='sales', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=100),
        ),
        migrations.CreateModel(
            name='SmtpConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_server', models.CharField(help_text='SMTP server address', max_length=255, verbose_name='SMTP Host')),
                ('smtp_port', models.PositiveIntegerField(help_text='SMTP server port', verbose_name='SMTP Port')),
                ('email_host_password', models.CharField(max_length=50, verbose_name='Password')),
                ('use_tls', models.BooleanField(default=True, verbose_name='Use TLS')),
                ('use_ssl', models.BooleanField(default=False, verbose_name='Use SSL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'SMTP Configuration',
                'verbose_name_plural': 'SMTP Configurations',
                'db_table': 'SmtpConfig',
            },
        ),
        migrations.CreateModel(
            name='UserVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_name', models.CharField(choices=[('position', 'Position'), ('sales_target', 'Sales Target')], max_length=50, verbose_name='Variable Name')),
                ('variable_value', models.CharField(max_length=250, verbose_name='Variable Value')),
                ('from_date', models.DateField(default=django.utils.timezone.now, verbose_name='From Date')),
                ('to_date', models.DateField(blank=True, null=True, verbose_name='To Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.profile', verbose_name='User')),
            ],
            options={
                'verbose_name': 'UserVariable',
                'verbose_name_plural': 'UserVariables',
                'db_table': 'UserVariable',
                'ordering': ['-from_date'],
            },
        ),
    ]
