# Generated by Django 5.0.9 on 2025-01-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_user_department_alter_user_role_smtpconfig_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('production', 'Production'), ('sales', 'Sales'), ('account', 'Account')], default='sales', max_length=100),
        ),
    ]
