# Generated by Django 5.0.9 on 2025-02-18 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_alter_profile_user_alter_smtpconfig_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('account', 'Account'), ('sales', 'Sales'), ('production', 'Production')], default='sales', max_length=100),
        ),
        migrations.AlterField(
            model_name='uservariable',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uservariable', to='teams.profile', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='uservariable',
            name='variable_name',
            field=models.CharField(choices=[('sales_target', 'Sales Target'), ('position', 'Position')], max_length=50, verbose_name='Variable Name'),
        ),
    ]
