# Generated by Django 5.0.9 on 2025-06-17 15:07

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_alter_user_department_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='employee_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='employee code'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='male', max_length=50, verbose_name='gender'),
        ),
        migrations.AddField(
            model_name='uservariable',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_edited',
            field=models.DateTimeField(auto_now=True, verbose_name='last edited'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('account', 'Account'), ('production', 'Production'), ('sales', 'Sales')], default='sales', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('sub-admin', 'Sub-admin'), ('user', 'User')], default='user', max_length=100),
        ),
        migrations.AlterField(
            model_name='uservariable',
            name='variable_name',
            field=models.CharField(choices=[('position', 'Position'), ('sales_target', 'Sales Target')], max_length=50, verbose_name='Variable Name'),
        ),
        migrations.AlterUniqueTogether(
            name='uservariable',
            unique_together={('user_profile', 'variable_name', 'from_date', 'is_active')},
        ),
    ]
