# Generated by Django 5.0.9 on 2025-09-05 12:52

import teams.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_profile_created_at_profile_employee_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to=teams.models.user_profile_path, verbose_name='Profile'),
        ),
    ]
