# version: "3.8"  # This can be removed if you're using Docker Compose v2

services:
  django_app:
    build: .
    container_name: django_app
    restart: always
    env_file: .env
    depends_on:
      - redis
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: gunicorn -b 0.0.0.0:8000 becrm.wsgi:application

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery:
    build: .
    container_name: celery_worker
    restart: always
    env_file: .env
    depends_on:
      - redis
      - django_app
    command: celery -A becrm worker --loglevel=info

  celery-beat:
    build: .
    container_name: celery_beat
    restart: always
    env_file: .env
    depends_on:
      - redis
      - django_app
      - celery
    command: celery -A becrm beat --loglevel=info

volumes:
  redis_data:
