# Generated by Django 5.0.3 on 2024-03-20 14:59

import django.core.validators
import sample.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(default=sample.models.sample_no, max_length=50, unique=True)),
                ('country', models.CharField(default='India', max_length=100)),
                ('report_format', models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('sez', 'SEZ')], default='monthly', max_length=100, verbose_name='Format')),
                ('report_type', models.CharField(choices=[('export', 'Export'), ('import', 'Import')], default='export', max_length=100, verbose_name='Type')),
                ('hs_code', models.CharField(blank=True, default='%', max_length=100)),
                ('product', models.CharField(blank=True, default='%', max_length=100)),
                ('iec', models.CharField(blank=True, default='%', max_length=100, verbose_name='IEC')),
                ('shipper', models.CharField(blank=True, default='%', max_length=255)),
                ('consignee', models.CharField(blank=True, default='%', max_length=255)),
                ('foreign_country', models.CharField(blank=True, default='%', max_length=255)),
                ('port', models.CharField(blank=True, default='%', max_length=255)),
                ('month', models.SmallIntegerField(blank=True, choices=[(1, 'Jan'), (2, 'Feb'), (3, 'Mar'), (4, 'Apr'), (5, 'May'), (6, 'Jun'), (7, 'Jul'), (8, 'Aug'), (9, 'Sep'), (10, 'Oct'), (11, 'Nov'), (12, 'Dec')], default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(13)])),
                ('year', models.SmallIntegerField(blank=True, default=sample.models.current_year, validators=[django.core.validators.MinValueValidator(2010), django.core.validators.MaxValueValidator(sample.models.current_year)])),
                ('client_name', models.CharField(max_length=100, verbose_name='Client Name')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('received', 'Received'), ('reject', 'Reject')], default='pending', max_length=50)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Sample',
                'verbose_name_plural': 'Samples',
                'ordering': ['sample_id'],
            },
        ),
    ]
