# Generated by Django 5.0.3 on 2024-03-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
