# Generated by Django 5.0.3 on 2024-04-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0006_alter_sample_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portmaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('port', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Port', max_length=255, null=True)),
                ('mode', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('ismonthly', models.BooleanField(blank=True, null=True)),
                ('isweekly', models.BooleanField(blank=True, null=True)),
                ('issez', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'portmaster',
                'managed': False,
            },
        ),
    ]
