# Generated by Django 5.0.3 on 2024-04-18 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0007_portmaster'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portmaster',
            options={'managed': True},
        ),
    ]
