# Generated by Django 5.0.3 on 2024-06-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0008_alter_portmaster_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10, null=True)),
                ('country', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'country_master',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='portmaster',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sample',
            name='report_format',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('sez', 'SEZ'), ('incoterm', 'Incoterm')], default='monthly', max_length=100, verbose_name='Format'),
        ),
    ]
