# Generated by Django 5.0.9 on 2025-06-17 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0009_countrymaster_alter_portmaster_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countrymaster',
            options={'managed': True},
        ),
    ]
