# Generated by Django 5.0.9 on 2025-02-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0010_alter_countrymaster_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrymaster',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='is active'),
        ),
    ]
