# Generated by Django 5.0.9 on 2025-08-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0011_countrymaster_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrymaster',
            name='can_process',
            field=models.BooleanField(default=False, verbose_name='can process'),
        ),
    ]
