# Generated by Django 5.0.9 on 2025-06-17 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="biller",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "biller_name",
                            models.CharField(
                                max_length=150, verbose_name="Biller Name"
                            ),
                        ),
                        (
                            "brand_name",
                            models.CharField(
                                blank=True,
                                max_length=150,
                                null=True,
                                verbose_name="Brand Name",
                            ),
                        ),
                        (
                            "biller_gstin",
                            models.CharField(
                                blank=True,
                                max_length=20,
                                null=True,
                                verbose_name="Biller Gstin",
                            ),
                        ),
                        (
                            "biller_pan",
                            models.CharField(
                                blank=True,
                                max_length=15,
                                null=True,
                                verbose_name="Biller Pan",
                            ),
                        ),
                        (
                            "biller_msme",
                            models.CharField(
                                blank=True,
                                max_length=150,
                                null=True,
                                verbose_name="Biller MSME",
                            ),
                        ),
                        (
                            "reg_address1",
                            models.CharField(
                                max_length=254, verbose_name="Reg. Address Line1"
                            ),
                        ),
                        (
                            "reg_address2",
                            models.CharField(
                                max_length=254, verbose_name="Reg. Address Line2"
                            ),
                        ),
                        (
                            "reg_city",
                            models.CharField(max_length=254, verbose_name="Reg. City"),
                        ),
                        (
                            "reg_state",
                            models.CharField(max_length=254, verbose_name="Reg. State"),
                        ),
                        (
                            "reg_pincode",
                            models.CharField(
                                max_length=254, verbose_name="Reg. Pincode"
                            ),
                        ),
                        (
                            "reg_country",
                            models.CharField(
                                max_length=254, verbose_name="Reg. Country"
                            ),
                        ),
                        (
                            "corp_address1",
                            models.CharField(
                                blank=True,
                                max_length=254,
                                null=True,
                                verbose_name="Corp. Address Line1",
                            ),
                        ),
                        (
                            "corp_address2",
                            models.CharField(
                                blank=True,
                                max_length=254,
                                null=True,
                                verbose_name="Corp. Address Line2",
                            ),
                        ),
                        (
                            "corp_city",
                            models.CharField(
                                blank=True,
                                max_length=254,
                                null=True,
                                verbose_name="Corp. City",
                            ),
                        ),
                        (
                            "corp_state",
                            models.CharField(
                                blank=True,
                                max_length=254,
                                null=True,
                                verbose_name="Corp. State",
                            ),
                        ),
                        (
                            "corp_pincode",
                            models.CharField(
                                blank=True,
                                max_length=254,
                                null=True,
                                verbose_name="Corp. Pincode",
                            ),
                        ),
                        (
                            "corp_country",
                            models.CharField(
                                blank=True,
                                max_length=254,
                                null=True,
                                verbose_name="Corp. Country",
                            ),
                        ),
                        (
                            "inserted_at",
                            models.DateTimeField(
                                auto_now=True, verbose_name="Inserted"
                            ),
                        ),
                        (
                            "edited_at",
                            models.DateTimeField(
                                auto_now_add=True, verbose_name="Edited"
                            ),
                        ),
                        (
                            "inserted_by",
                            models.IntegerField(verbose_name="Inserted By"),
                        ),
                    ],
                    options={
                        "verbose_name": "Biller",
                        "verbose_name_plural": "Billers",
                        "db_table": "Biller",
                        # "unique_together": {("biller_name", "biller_gstin")},
                    },
                ),
                migrations.CreateModel(
                    name="BillerVariable",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "variable_name",
                            models.CharField(
                                choices=[
                                    ("pi_tag", "PI Tag"),
                                    ("pi_format", "PI Format"),
                                    ("invoice_tag", "Invoice Tag"),
                                    ("invoice_format", "Invoice Format"),
                                ],
                                max_length=50,
                                verbose_name="Variable Name",
                            ),
                        ),
                        (
                            "variable_value",
                            models.CharField(
                                max_length=150, verbose_name="Variable Value"
                            ),
                        ),
                        ("from_date", models.DateField(verbose_name="From Date")),
                        (
                            "to_date",
                            models.DateField(
                                blank=True, null=True, verbose_name="To Date"
                            ),
                        ),
                        (
                            "inserted_by",
                            models.IntegerField(verbose_name="Inserted By"),
                        ),
                        (
                            "Inserted_at",
                            models.DateTimeField(
                                auto_now_add=True, verbose_name="Inserted At"
                            ),
                        ),
                        (
                            "biller_id",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="variables",
                                to="billers.biller",
                                verbose_name="Biller Id",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Biller Variable",
                        "verbose_name_plural": "Biller Variables",
                        "db_table": "Biller_Variable",
                    },
                ),
                migrations.CreateModel(
                    name="bankDetail",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "is_active",
                            models.BooleanField(default=True, verbose_name="Is Active"),
                        ),
                        (
                            "is_upi",
                            models.BooleanField(default=False, verbose_name="Is UPI"),
                        ),
                        (
                            "upi_id",
                            models.CharField(
                                blank=True,
                                max_length=50,
                                null=True,
                                verbose_name="UPI ID",
                            ),
                        ),
                        (
                            "upi_no",
                            models.CharField(
                                blank=True,
                                max_length=50,
                                null=True,
                                verbose_name="UPI No",
                            ),
                        ),
                        (
                            "bnf_name",
                            models.CharField(
                                max_length=150, verbose_name="Beneficiary Name"
                            ),
                        ),
                        (
                            "bank_name",
                            models.CharField(max_length=150, verbose_name="Bank Name"),
                        ),
                        (
                            "branch_address",
                            models.CharField(
                                blank=True,
                                max_length=254,
                                null=True,
                                verbose_name="Branch Address",
                            ),
                        ),
                        (
                            "ac_no",
                            models.CharField(max_length=150, verbose_name="A/c No"),
                        ),
                        ("ifsc", models.CharField(max_length=50, verbose_name="IFSC")),
                        (
                            "swift_code",
                            models.CharField(
                                blank=True,
                                max_length=50,
                                null=True,
                                verbose_name="Swift Code",
                            ),
                        ),
                        (
                            "inserted_at",
                            models.DateTimeField(
                                auto_now_add=True, verbose_name="Inserted at"
                            ),
                        ),
                        (
                            "edited_at",
                            models.DateTimeField(
                                auto_now=True, verbose_name="Edited at"
                            ),
                        ),
                        (
                            "inserted_by",
                            models.IntegerField(verbose_name="Inserted By"),
                        ),
                        (
                            "biller_id",
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                to="billers.biller",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Bank",
                        "verbose_name_plural": "Banks",
                        "db_table": "Bank_List",
                        "unique_together": {
                            ("bnf_name", "bank_name", "ac_no", "upi_id", "upi_no")
                        },
                    },
                ),
            ],
        )
    ]
