# Generated by Django 5.0.9 on 2025-08-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biller',
            name='branch_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='branch id'),
        ),
    ]
