# Generated by Django 5.0.9 on 2025-09-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billers', '0002_biller_branch_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biller',
            old_name='branch_id',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='bankdetail',
            old_name='biller_id',
            new_name='biller',
        ),
        migrations.AddField(
            model_name='bankdetail',
            name='branch',
            field=models.IntegerField(blank=True, null=True, verbose_name='branch'),
        ),
        migrations.AlterField(
            model_name='biller',
            name='edited_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Edited'),
        ),
        migrations.AlterField(
            model_name='biller',
            name='inserted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Inserted'),
        ),
    ]
