# Generated by Django 5.0.9 on 2025-11-05 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billers', '0003_rename_branch_id_biller_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetail',
            name='ac_no',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='A/c No'),
        ),
        migrations.AlterField(
            model_name='bankdetail',
            name='bank_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Bank Name'),
        ),
        migrations.AlterField(
            model_name='bankdetail',
            name='biller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banks', to='billers.biller'),
        ),
        migrations.AlterField(
            model_name='bankdetail',
            name='ifsc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='IFSC'),
        ),
        migrations.AlterField(
            model_name='biller',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Edited'),
        ),
        migrations.AddConstraint(
            model_name='biller',
            constraint=models.UniqueConstraint(fields=('biller_name', 'biller_gstin', 'branch'), name='unique_biller_name_gstin_branch'),
        ),
    ]
