# Generated by Django 5.0.9 on 2025-12-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billers', '0004_alter_bankdetail_ac_no_alter_bankdetail_bank_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bankdetail',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bankdetail',
            name='upi_qr',
            field=models.ImageField(blank=True, null=True, upload_to='upi_qr_code/', verbose_name='upi qr'),
        ),
        migrations.AlterField(
            model_name='billervariable',
            name='variable_name',
            field=models.CharField(choices=[('pi_tag', 'PI Tag'), ('pi_format', 'PI Format'), ('invoice_tag', 'Invoice Tag'), ('invoice_format', 'Invoice Format'), ('website', 'Website')], max_length=50, verbose_name='Variable Name'),
        ),
        migrations.AddConstraint(
            model_name='bankdetail',
            constraint=models.UniqueConstraint(fields=('bnf_name', 'bank_name', 'ac_no', 'upi_id', 'upi_no', 'branch'), name='unique_bnf_bank_ac_upi_id_no_branch'),
        ),
    ]
