# Generated by Django 5.0.9 on 2025-12-04 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0008_alter_profile_profile_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_type', models.CharField(choices=[('biller', 'Biller'), ('bank', 'Bank'), ('customer', 'Customer'), ('other', 'Other')], max_length=50, verbose_name='owner_type')),
                ('owner_id', models.PositiveIntegerField(verbose_name='owner_id')),
                ('doc_type', models.CharField(choices=[('signature', 'Signature'), ('stamp', 'Stamp'), ('gst', 'GST Certificate'), ('msme', 'MSME Certificate'), ('other', 'Other')], max_length=50, verbose_name='Document type')),
                ('file', models.FileField(upload_to='', verbose_name='file')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploaded at')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='teams.branch', verbose_name='branch')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='BranchLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('CATEGORY', 'Category'), ('REPORT_TYPE', 'Report type')], max_length=50, verbose_name='group')),
                ('key_value', models.CharField(max_length=50, verbose_name='key value')),
                ('label', models.CharField(max_length=200, verbose_name='label')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branchlabels', to='teams.branch', verbose_name='branch')),
            ],
            options={
                'db_table': 'branchlabel',
                'indexes': [models.Index(fields=['branch'], name='branchlabel_branch__704547_idx'), models.Index(fields=['branch', 'group'], name='branchlabel_branch__d16c28_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='branchlabel',
            constraint=models.UniqueConstraint(fields=('branch', 'group', 'key_value'), name='unique_branch_group_key_value'),
        ),
    ]
