# Generated by Django 5.0.3 on 2024-05-28 11:42

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=50, verbose_name='Contact Person')),
                ('email_id', models.CharField(blank=True, max_length=155, null=True, verbose_name='Email Id')),
                ('contact_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Contact No')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('edited_at', models.DateTimeField(auto_now=True, verbose_name='Edited at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Contact Person',
                'verbose_name_plural': 'Contact Persons',
                'db_table': 'ContactPersons',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Tittle')),
                ('start_at', models.DateTimeField(auto_now_add=True, verbose_name='Started at')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'db_table': 'Conversations',
            },
        ),
        migrations.CreateModel(
            name='leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150, verbose_name='Company Name')),
                ('gstin', models.CharField(blank=True, max_length=16, null=True, verbose_name='GSTIN')),
                ('address1', models.CharField(max_length=255, verbose_name='Address Line 1')),
                ('address2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 2')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('state', models.CharField(max_length=255, verbose_name='State')),
                ('country', models.CharField(max_length=255, verbose_name='Country')),
                ('pincode', models.CharField(blank=True, max_length=255, null=True, verbose_name='Pin Code')),
                ('industry', models.CharField(blank=True, max_length=255, null=True, verbose_name='Industry')),
                ('source', models.CharField(choices=[('whatsapp', 'Whatsapp'), ('email', 'Email'), ('linkedin', 'Linkedin'), ('pepo', 'Pepo'), ('calling', 'Calling'), ('others', 'Others')], default='email', max_length=50, verbose_name='Source')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('edited_at', models.DateTimeField(auto_now=True, verbose_name='Edited at')),
                ('user', models.IntegerField(verbose_name='User Id')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'db_table': 'Leads',
            },
        ),
        migrations.CreateModel(
            name='conversationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Details')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('lost', 'Lost')], default='open', max_length=50, verbose_name='Status')),
                ('follow_up', models.DateField(blank=True, null=True, verbose_name='Next Follow Up')),
                ('inserted_at', models.DateTimeField(auto_now_add=True, verbose_name='Inserted at')),
                ('edited_at', models.DateTimeField(auto_now=True, verbose_name='Edited at')),
                ('chat_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead.conversation', verbose_name='Chat No')),
                ('contact_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead.contactperson', verbose_name='Contact Person')),
            ],
            options={
                'verbose_name': 'Conversation Detail',
                'verbose_name_plural': 'Conversation Details',
                'db_table': 'ConversationDetails',
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead.leads', verbose_name='Company Id'),
        ),
        migrations.AddField(
            model_name='contactperson',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead.leads', verbose_name='Company Id'),
        ),
    ]
