# Generated by Django 5.0.3 on 2024-07-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='leads',
            index=models.Index(fields=['gstin', 'company_name'], name='Leads_gstin_916318_idx'),
        ),
        migrations.AddIndex(
            model_name='leads',
            index=models.Index(fields=['company_name'], name='company_name_idx'),
        ),
    ]
