# Generated by Django 5.0.3 on 2024-05-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationdetails',
            name='details',
            field=models.TextField(verbose_name='Details'),
        ),
    ]
