# Generated by Django 5.0.3 on 2024-06-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_alter_conversationdetails_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='source',
            field=models.CharField(choices=[('whatsapp', 'Whatsapp'), ('email', 'Email'), ('linkedin', 'Linkedin'), ('campaign', 'Campaign'), ('calling', 'Calling'), ('others', 'Others')], default='email', max_length=50, verbose_name='Source'),
        ),
        migrations.AlterUniqueTogether(
            name='leads',
            unique_together={('company_name', 'gstin', 'user')},
        ),
    ]
