# Generated by Django 5.0.9 on 2025-02-18 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_leads_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactperson',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactpersons', to='lead.leads', verbose_name='Company Id'),
        ),
        migrations.AlterField(
            model_name='conversationdetails',
            name='chat_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversationdetails', to='lead.conversation', verbose_name='Chat No'),
        ),
    ]
