# Generated by Django 5.0.9 on 2025-02-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0003_alter_contactperson_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='full_address',
            field=models.CharField(blank=True, max_length=512, verbose_name='full address'),
        ),
    ]
