# Generated by Django 5.0.9 on 2025-07-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0004_leads_full_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundLeads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('company_name', models.CharField(max_length=50, verbose_name='company name')),
                ('location', models.CharField(blank=True, max_length=50, null=True, verbose_name='location')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('contact_no', models.CharField(max_length=50, verbose_name='contact no')),
                ('message', models.TextField(max_length=1000, verbose_name='message')),
                ('source', models.CharField(max_length=50, verbose_name='source')),
                ('assigned_to', models.IntegerField(blank=True, null=True, verbose_name='assigned to')),
                ('assigned_by', models.IntegerField(blank=True, null=True, verbose_name='assigned by')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'inboundlead',
                'verbose_name_plural': 'inboundleads',
                'db_table': 'Inboundleads',
            },
        ),
        migrations.AlterField(
            model_name='leads',
            name='source',
            field=models.CharField(default='email', max_length=50, verbose_name='Source'),
        ),
    ]
