# Generated by Django 5.0.9 on 2025-09-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0005_inboundleads_alter_leads_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactperson',
            name='branch',
            field=models.IntegerField(blank=True, null=True, verbose_name='branch'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='branch',
            field=models.IntegerField(blank=True, null=True, verbose_name='branch'),
        ),
        migrations.AddField(
            model_name='inboundleads',
            name='branch',
            field=models.IntegerField(blank=True, null=True, verbose_name='branch'),
        ),
        migrations.AddField(
            model_name='leads',
            name='branch',
            field=models.IntegerField(blank=True, null=True, verbose_name='branch'),
        ),
    ]
