# Generated by Django 5.0.3 on 2024-07-23 16:03

import django.db.models.deletion
import invoice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lead', '0002_leads_leads_gstin_916318_idx_leads_company_name_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='biller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biller_name', models.CharField(max_length=150, verbose_name='Biller Name')),
                ('biller_gstin', models.CharField(blank=True, max_length=150, null=True, verbose_name='Biller Gstin')),
                ('biller_msme', models.CharField(blank=True, max_length=150, null=True, verbose_name='Biller MSME')),
                ('reg_address1', models.CharField(max_length=254, verbose_name='Reg. Address Line1')),
                ('reg_address2', models.CharField(max_length=254, verbose_name='Reg. Address Line2')),
                ('reg_city', models.CharField(max_length=254, verbose_name='Reg. City')),
                ('reg_state', models.CharField(max_length=254, verbose_name='Reg. State')),
                ('reg_pincode', models.CharField(max_length=254, verbose_name='Reg. Pincode')),
                ('reg_country', models.CharField(max_length=254, verbose_name='Reg. Country')),
                ('corp_address1', models.CharField(blank=True, max_length=254, null=True, verbose_name='Corp. Address Line1')),
                ('corp_address2', models.CharField(blank=True, max_length=254, null=True, verbose_name='Corp. Address Line2')),
                ('corp_city', models.CharField(blank=True, max_length=254, null=True, verbose_name='Corp. City')),
                ('corp_state', models.CharField(blank=True, max_length=254, null=True, verbose_name='Corp. State')),
                ('corp_pincode', models.CharField(blank=True, max_length=254, null=True, verbose_name='Corp. Pincode')),
                ('corp_country', models.CharField(blank=True, max_length=254, null=True, verbose_name='Corp. Country')),
                ('inserted_at', models.DateTimeField(auto_now=True, verbose_name='Inserted')),
                ('edited_at', models.DateTimeField(auto_now_add=True, verbose_name='Edited')),
            ],
            options={
                'verbose_name': 'Biller',
                'verbose_name_plural': 'Billers',
                'db_table': 'Biller',
                'unique_together': {('biller_name', 'biller_gstin')},
            },
        ),
        migrations.CreateModel(
            name='bankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bnf_name', models.CharField(max_length=150, verbose_name='Beneficiary Name')),
                ('bank_name', models.CharField(max_length=150, verbose_name='Bank Name')),
                ('branch_address', models.CharField(blank=True, max_length=254, null=True, verbose_name='Branch Address')),
                ('ac_no', models.CharField(max_length=150, verbose_name='A/c No')),
                ('ifsc', models.CharField(max_length=50, verbose_name='IFSC')),
                ('swift_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Swift Code')),
                ('biller_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.biller')),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Banks',
                'db_table': 'Bank_List',
                'unique_together': {('bnf_name', 'bank_name', 'ac_no')},
            },
        ),
        migrations.CreateModel(
            name='proforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='User Id')),
                ('company_name', models.CharField(max_length=150, verbose_name='Company Name')),
                ('gstin', models.CharField(blank=True, max_length=50, null=True, verbose_name='GSTIN')),
                ('address', models.TextField(max_length=1000, verbose_name='Address')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('requistioner', models.CharField(max_length=50, verbose_name='Requistioner')),
                ('email_id', models.EmailField(max_length=254, verbose_name='Email')),
                ('contact', models.CharField(max_length=50, verbose_name='Contact No')),
                ('pi_no', models.CharField(default=invoice.models.pi_number, max_length=50, unique=True, verbose_name='PI No')),
                ('pi_date', models.DateField(auto_now=True, verbose_name='PI Date')),
                ('po_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='PO No')),
                ('po_date', models.DateField(blank=True, null=True, verbose_name='PO Date')),
                ('subscription', models.CharField(max_length=50, verbose_name='Subscription Mode')),
                ('payment_term', models.CharField(max_length=50, verbose_name='Payment Term')),
                ('currency', models.CharField(max_length=50, verbose_name='Currency')),
                ('details', models.TextField(max_length=1000, verbose_name='Details')),
                ('is_Approved', models.BooleanField(default=False, verbose_name='Is_Approved')),
                ('approved_by', models.IntegerField(blank=True, verbose_name='Approved By')),
                ('approved_at', models.DateTimeField(auto_now_add=True, verbose_name='Approved At')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created At')),
                ('edited_at', models.DateTimeField(auto_now_add=True, verbose_name='Edited At')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='invoice.bankdetail')),
                ('company_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='lead.leads', verbose_name='Company Ref')),
            ],
            options={
                'verbose_name': 'proforma',
                'verbose_name_plural': 'proformas',
                'db_table': 'Proforma_Invoice',
            },
        ),
        migrations.CreateModel(
            name='orderList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='Category')),
                ('report_type', models.CharField(max_length=50, verbose_name='Report Type')),
                ('product', models.CharField(max_length=50, verbose_name='Product')),
                ('from_month', models.CharField(max_length=50, verbose_name='From Month')),
                ('to_month', models.CharField(max_length=50, verbose_name='To Month')),
                ('unit_price', models.IntegerField(blank=True, verbose_name='Unit Price')),
                ('total_price', models.IntegerField(blank=True, verbose_name='Total Price')),
                ('lumpsum_amt', models.IntegerField(blank=True, verbose_name='Lumpsum')),
                ('is_lumpsum', models.BooleanField(default=False, verbose_name='Is_Lumpsum')),
                ('order_status', models.CharField(max_length=50, verbose_name='Order Status')),
                ('inserted_at', models.DateTimeField(auto_now=True, verbose_name='Inserted At')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated At')),
                ('proforma_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='invoice.proforma')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'Order_List',
            },
        ),
    ]
