# Generated by Django 5.0.3 on 2024-09-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biller',
            name='biller_pan',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Biller Pan'),
        ),
        migrations.AlterField(
            model_name='biller',
            name='biller_gstin',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Biller Gstin'),
        ),
    ]
