# Generated by Django 5.0.9 on 2024-12-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proforma',
            options={'permissions': [('can_proforma_approve', 'Can approve Proforma Invoice')], 'verbose_name': 'proforma', 'verbose_name_plural': 'proformas'},
        ),
        migrations.AlterField(
            model_name='processedorder',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('complete', 'Complete')], default='pending', max_length=50, verbose_name='Order Status'),
        ),
    ]
