# Generated by Django 5.0.3 on 2024-07-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proforma',
            name='approved_by',
            field=models.IntegerField(blank=True, null=True, verbose_name='Approved By'),
        ),
    ]
