# Generated by Django 5.0.3 on 2024-09-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_biller_biller_pan_alter_biller_biller_gstin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='product',
            field=models.CharField(max_length=255, verbose_name='Product'),
        ),
    ]
