# Generated by Django 5.0.3 on 2024-07-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_alter_proforma_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='proforma',
            name='status',
            field=models.CharField(default='open', max_length=50, verbose_name='Status'),
        ),
    ]
