# Generated by Django 5.0.9 on 2025-01-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_alter_proforma_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetail',
            name='inserted_by',
            field=models.IntegerField(default=1, verbose_name='Inserted By'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biller',
            name='inserted_by',
            field=models.IntegerField(default=1, verbose_name='Inserted By'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proforma',
            name='additional_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Additional Emails'),
        ),
        migrations.AddField(
            model_name='proforma',
            name='feedback',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='feedback'),
        ),
    ]
