# Generated by Django 5.0.3 on 2024-09-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_alter_orderlist_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='product',
            field=models.CharField(max_length=500, verbose_name='Product'),
        ),
    ]
