# Generated by Django 5.0.9 on 2025-02-18 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_bankdetail_inserted_by_biller_inserted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proforma',
            name='user_contact',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='User Contact'),
        ),
        migrations.AddField(
            model_name='proforma',
            name='user_email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='User Email'),
        ),
        migrations.AddField(
            model_name='proforma',
            name='user_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Team Member'),
        ),
        migrations.AlterField(
            model_name='billervariable',
            name='biller_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='invoice.biller', verbose_name='Biller Id'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='proforma_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orderlist', to='invoice.proforma'),
        ),
    ]
