# Generated by Django 5.0.9 on 2025-06-17 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0004_proforma_user_contact_proforma_user_email_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="convertedpi",
            old_name="invoice_no",
            new_name="formatted_invoice",
        ),
        migrations.AddField(
            model_name="convertedpi",
            name="invoice_number",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="invoice number"
            ),
        ),
        migrations.AlterField(
            model_name="convertedpi",
            name="pi_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="convertedpi",
                to="invoice.proforma",
                verbose_name="PI ID",
            ),
        ),
        migrations.AlterField(
            model_name="processedorder",
            name="pi_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="processedorders",
                to="invoice.proforma",
                verbose_name="PI ID",
            ),
        ),
        migrations.CreateModel(
            name="PiSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="subtotal"
                    ),
                ),
                (
                    "cgst_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=4,
                        verbose_name="cgst rate",
                    ),
                ),
                (
                    "sgst_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=4,
                        verbose_name="sgst rate",
                    ),
                ),
                (
                    "igst_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=4,
                        verbose_name="igst rate",
                    ),
                ),
                (
                    "total_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="total_value"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="last updated"),
                ),
                (
                    "proforma",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summary",
                        to="invoice.proforma",
                        verbose_name="proforma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pi Summary",
                "verbose_name_plural": "Pi Summary",
                "db_table": "PiSummary",
            },
        ),
    ]
