# Generated by Django 5.0.9 on 2025-06-17 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billers", "0001_initial"),
        ("invoice", "0005_rename_convertedpi_invoice_no_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proforma",
            name="bank",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="billers.bankdetail"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="biller",
            unique_together=None,
        ),
        # migrations.RemoveField(
        #     model_name="billervariable",
        #     name="biller_id",
        # ),
        migrations.AlterField(
            model_name="convertedpi",
            name="formatted_invoice",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="formatted invoice"
            ),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name="bankDetail",
                ),
                migrations.DeleteModel(
                    name="biller",
                ),
                migrations.DeleteModel(
                    name="BillerVariable",
                ),
            ],
        ),
    ]
