# Generated by Django 5.0.3 on 2024-09-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_proforma_edited_by_proforma_is_sez_proforma_lut_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proforma',
            name='pi_date',
            field=models.DateField(auto_now_add=True, verbose_name='PI Date'),
        ),
    ]
