# Generated by Django 5.0.3 on 2024-10-19 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_alter_proforma_status_convertedpi_processedorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convertedpi',
            name='payment_status',
            field=models.CharField(choices=[('Full', 'Full'), ('credit', 'Credit'), ('partial', 'Partial')], max_length=50, verbose_name='Payment Status'),
        ),
        migrations.AlterField(
            model_name='convertedpi',
            name='pi_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.proforma', unique=True, verbose_name='PI ID'),
        ),
        migrations.AlterField(
            model_name='processedorder',
            name='format',
            field=models.CharField(choices=[('incoterm', 'Incoterm'), ('sez(weekly)', 'SEZ (Weekly)'), ('weekly', 'weekly'), ('monthly', 'Monthly'), ('10 days', '10 Days'), ('sez', 'SEZ')], max_length=250, verbose_name='Format'),
        ),
        migrations.AlterField(
            model_name='processedorder',
            name='report_type',
            field=models.CharField(choices=[('online', 'Subscription'), ('export', 'Outbound Insight'), ('domestic', 'Market Research'), ('import', 'Inbound Insight')], max_length=150, verbose_name='Report Type'),
        ),
    ]
