# Generated by Django 5.0.3 on 2024-09-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_alter_proforma_pi_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='proforma',
            name='closed_at',
            field=models.DateField(blank=True, null=True, verbose_name='Closing Date'),
        ),
    ]
