# Generated by Django 5.0.9 on 2025-06-19 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billers', '0001_initial'),
        ('invoice', '0006_alter_proforma_bank_alter_biller_unique_together_and_more'),
        ('lead', '0004_leads_full_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='convertedpi',
            name='generated_by',
            field=models.IntegerField(blank=True, null=True, verbose_name='invoice generated by'),
        ),
        migrations.AddField(
            model_name='convertedpi',
            name='updated_by',
            field=models.IntegerField(blank=True, null=True, verbose_name='updated_by'),
        ),
        migrations.AddField(
            model_name='orderlist',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='pisummary',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='discount'),
        ),
        migrations.AddField(
            model_name='pisummary',
            name='offline_sale',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='offline sale'),
        ),
        migrations.AddField(
            model_name='pisummary',
            name='online_sale',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='online sale'),
        ),
        migrations.AddField(
            model_name='pisummary',
            name='other_sale',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='other sale'),
        ),
        migrations.AddField(
            model_name='processedorder',
            name='plan',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='plan'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='unit_price',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='processedorder',
            name='last_sent_date',
            field=models.DateField(blank=True, null=True, verbose_name='last sent date'),
        ),
        migrations.AlterField(
            model_name='processedorder',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='order date'),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='additional_email',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Additional Emails'),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='proformas', to='billers.bankdetail'),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='company_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='proformas', to='lead.leads', verbose_name='Company Ref'),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='contact',
            field=models.CharField(blank=True, max_length=50, verbose_name='Contact No'),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='email_id',
            field=models.CharField(blank=True, max_length=254, verbose_name='Email'),
        ),
    ]
