# Generated by Django 5.0.3 on 2024-10-19 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_alter_convertedpi_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convertedpi',
            name='pi_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='invoice.proforma', verbose_name='PI ID'),
        ),
        migrations.AlterField(
            model_name='processedorder',
            name='format',
            field=models.CharField(choices=[('10 days', '10 Days'), ('sez', 'SEZ'), ('sez(weekly)', 'SEZ (Weekly)'), ('incoterm', 'Incoterm'), ('monthly', 'Monthly'), ('weekly', 'weekly')], max_length=250, verbose_name='Format'),
        ),
        migrations.AlterField(
            model_name='processedorder',
            name='report_type',
            field=models.CharField(choices=[('import', 'Inbound Insight'), ('online', 'Subscription'), ('domestic', 'Market Research'), ('export', 'Outbound Insight')], max_length=150, verbose_name='Report Type'),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='status',
            field=models.CharField(choices=[('lost', 'LOST'), ('closed', 'CLOSED'), ('open', 'OPEN')], default='open', max_length=50, verbose_name='Status'),
        ),
    ]
