# Generated by Django 5.0.3 on 2024-10-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_alter_convertedpi_pi_id_alter_processedorder_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='convertedpi',
            name='invoice_date',
            field=models.DateField(blank=True, null=True, verbose_name='Invoice Date'),
        ),
        migrations.AddField(
            model_name='convertedpi',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Invoice No'),
        ),
        migrations.AddField(
            model_name='convertedpi',
            name='irn',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='IRN'),
        ),
        migrations.AddField(
            model_name='convertedpi',
            name='is_invoiceRequire',
            field=models.BooleanField(default=False, verbose_name='Is Invoice Required'),
        ),
        migrations.AlterField(
            model_name='convertedpi',
            name='payment_status',
            field=models.CharField(choices=[('credit', 'Credit'), ('partial', 'Partial'), ('full', 'Full')], max_length=50, verbose_name='Payment Status'),
        ),
        migrations.AlterField(
            model_name='processedorder',
            name='format',
            field=models.CharField(choices=[('sez(weekly)', 'SEZ (Weekly)'), ('weekly', 'weekly'), ('monthly', 'Monthly'), ('10 days', '10 Days'), ('incoterm', 'Incoterm'), ('sez', 'SEZ')], max_length=250, verbose_name='Format'),
        ),
        migrations.AlterField(
            model_name='processedorder',
            name='order_status',
            field=models.CharField(choices=[('complete', 'Complete'), ('pending', 'Pending')], default='pending', max_length=50, verbose_name='Order Status'),
        ),
        migrations.AlterField(
            model_name='processedorder',
            name='report_type',
            field=models.CharField(choices=[('online', 'Subscription'), ('export', 'Outbound Insight'), ('domestic', 'Market Research'), ('import', 'Inbound Insight')], max_length=150, verbose_name='Report Type'),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='status',
            field=models.CharField(choices=[('open', 'OPEN'), ('lost', 'LOST'), ('closed', 'CLOSED')], default='open', max_length=50, verbose_name='Status'),
        ),
    ]
