# Generated by Django 5.0.9 on 2025-06-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billers', '0001_initial'),
        ('invoice', '0007_convertedpi_generated_by_convertedpi_updated_by_and_more'),
        ('lead', '0004_leads_full_address'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='convertedpi',
            index=models.Index(fields=['payment_status'], name='Converted_P_payment_645b18_idx'),
        ),
        migrations.AddIndex(
            model_name='convertedpi',
            index=models.Index(fields=['formatted_invoice'], name='Converted_P_formatt_f0cd2f_idx'),
        ),
        migrations.AddIndex(
            model_name='convertedpi',
            index=models.Index(fields=['invoice_number'], name='Converted_P_invoice_ccac82_idx'),
        ),
        migrations.AddIndex(
            model_name='convertedpi',
            index=models.Index(fields=['is_processed'], name='Converted_P_is_proc_dfae1d_idx'),
        ),
        migrations.AddIndex(
            model_name='convertedpi',
            index=models.Index(fields=['is_closed'], name='Converted_P_is_clos_ea2c0a_idx'),
        ),
        migrations.AddIndex(
            model_name='convertedpi',
            index=models.Index(fields=['invoice_date'], name='Converted_P_invoice_6f70fc_idx'),
        ),
        migrations.AddIndex(
            model_name='orderlist',
            index=models.Index(fields=['category'], name='Order_List_categor_b40f21_idx'),
        ),
        migrations.AddIndex(
            model_name='orderlist',
            index=models.Index(fields=['report_type'], name='Order_List_report__86a5d5_idx'),
        ),
        migrations.AddIndex(
            model_name='orderlist',
            index=models.Index(fields=['is_lumpsum'], name='Order_List_is_lump_3f379c_idx'),
        ),
        migrations.AddIndex(
            model_name='pisummary',
            index=models.Index(fields=['last_updated'], name='PiSummary_last_up_442daf_idx'),
        ),
        migrations.AddIndex(
            model_name='processedorder',
            index=models.Index(fields=['report_type'], name='Processed_O_report__5168dd_idx'),
        ),
        migrations.AddIndex(
            model_name='processedorder',
            index=models.Index(fields=['format'], name='Processed_O_format_41ff58_idx'),
        ),
        migrations.AddIndex(
            model_name='processedorder',
            index=models.Index(fields=['country'], name='Processed_O_country_22f5ea_idx'),
        ),
        migrations.AddIndex(
            model_name='processedorder',
            index=models.Index(fields=['order_status'], name='Processed_O_order_s_85650c_idx'),
        ),
        migrations.AddIndex(
            model_name='processedorder',
            index=models.Index(fields=['from_month', 'to_month'], name='Processed_O_from_mo_74d264_idx'),
        ),
        migrations.AddIndex(
            model_name='proforma',
            index=models.Index(fields=['user_id'], name='Proforma_In_user_id_54a036_idx'),
        ),
        migrations.AddIndex(
            model_name='proforma',
            index=models.Index(fields=['company_name'], name='Proforma_In_company_fde616_idx'),
        ),
        migrations.AddIndex(
            model_name='proforma',
            index=models.Index(fields=['gstin'], name='Proforma_In_gstin_08160e_idx'),
        ),
        migrations.AddIndex(
            model_name='proforma',
            index=models.Index(fields=['status'], name='Proforma_In_status_99019d_idx'),
        ),
        migrations.AddIndex(
            model_name='proforma',
            index=models.Index(fields=['created_at'], name='Proforma_In_created_1240da_idx'),
        ),
        migrations.AddIndex(
            model_name='proforma',
            index=models.Index(fields=['closed_at'], name='Proforma_In_closed__90660d_idx'),
        ),
        migrations.AddIndex(
            model_name='proforma',
            index=models.Index(fields=['is_Approved'], name='Proforma_In_is_Appr_53145f_idx'),
        ),
    ]
