# Generated by Django 5.0.9 on 2025-08-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_convertedpi_converted_p_payment_645b18_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedorder',
            name='report_type',
            field=models.CharField(max_length=150, verbose_name='Report Type'),
        ),
    ]
