# Generated by Django 5.0.3 on 2024-10-21 14:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_convertedpi_invoice_date_convertedpi_invoice_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='convertedpi',
            name='requested_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Requested At'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='convertedpi',
            name='payment_status',
            field=models.CharField(choices=[('full', 'Full'), ('partial', 'Partial'), ('credit', 'Credit')], max_length=50, verbose_name='Payment Status'),
        ),
        migrations.AlterField(
            model_name='processedorder',
            name='format',
            field=models.CharField(choices=[('incoterm', 'Incoterm'), ('monthly', 'Monthly'), ('weekly', 'weekly'), ('10 days', '10 Days'), ('sez', 'SEZ'), ('sez(weekly)', 'SEZ (Weekly)')], max_length=250, verbose_name='Format'),
        ),
        migrations.AlterField(
            model_name='processedorder',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete')], default='pending', max_length=50, verbose_name='Order Status'),
        ),
        migrations.AlterField(
            model_name='processedorder',
            name='report_type',
            field=models.CharField(choices=[('import', 'Inbound Insight'), ('online', 'Subscription'), ('domestic', 'Market Research'), ('export', 'Outbound Insight')], max_length=150, verbose_name='Report Type'),
        ),
    ]
