# Generated by Django 5.0.9 on 2025-09-01 11:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billers', '0003_rename_branch_id_biller_branch_and_more'),
        ('invoice', '0009_alter_processedorder_report_type'),
        ('lead', '0006_contactperson_branch_conversation_branch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlist',
            old_name='proforma_id',
            new_name='proforma',
        ),
        migrations.AddField(
            model_name='convertedpi',
            name='branch',
            field=models.IntegerField(blank=True, null=True, verbose_name='branch'),
        ),
        migrations.AddField(
            model_name='orderlist',
            name='branch',
            field=models.IntegerField(blank=True, null=True, verbose_name='branch'),
        ),
        migrations.AddField(
            model_name='pisummary',
            name='branch',
            field=models.IntegerField(blank=True, null=True, verbose_name='branch'),
        ),
        migrations.AddField(
            model_name='pisummary',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1.0, max_digits=12, verbose_name='exchange rate'),
        ),
        migrations.AddField(
            model_name='pisummary',
            name='total_amount_in_inr',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='total value (INR)'),
        ),
        migrations.AddField(
            model_name='processedorder',
            name='branch',
            field=models.IntegerField(blank=True, null=True, verbose_name='branch'),
        ),
        migrations.AddField(
            model_name='proforma',
            name='branch',
            field=models.IntegerField(blank=True, null=True, verbose_name='branch'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='inserted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Inserted At'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approved At'),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='pi_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='PI Date'),
        ),
        migrations.AddIndex(
            model_name='convertedpi',
            index=models.Index(fields=['branch'], name='Converted_P_branch_87a637_idx'),
        ),
        migrations.AddIndex(
            model_name='orderlist',
            index=models.Index(fields=['branch'], name='Order_List_branch_150973_idx'),
        ),
        migrations.AddIndex(
            model_name='pisummary',
            index=models.Index(fields=['branch'], name='PiSummary_branch_ddf0fa_idx'),
        ),
        migrations.AddIndex(
            model_name='processedorder',
            index=models.Index(fields=['branch'], name='Processed_O_branch_456c6b_idx'),
        ),
        migrations.AddIndex(
            model_name='proforma',
            index=models.Index(fields=['branch'], name='Proforma_In_branch_c5367d_idx'),
        ),
    ]
