# Generated by Django 5.0.9 on 2025-10-31 12:09

import invoice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_rename_proforma_id_orderlist_proforma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='convertedpi',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='processed_at'),
        ),
        migrations.AlterField(
            model_name='processedorder',
            name='format',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'weekly'), ('10 days', '10 Days'), ('sez', 'SEZ'), ('sez_with_incoterm', 'SEZ (Incoterms)'), ('incoterm', 'Incoterm')], max_length=250, verbose_name='Format'),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='pi_date',
            field=models.DateField(default=invoice.models.get_today, verbose_name='PI Date'),
        ),
    ]
