# Generated by Django 5.0.9 on 2025-11-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0011_convertedpi_processed_at_alter_processedorder_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proforma',
            name='renewal_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('renewed', 'Renewed'), ('renew_cancel', 'Renew Cancel')], default='pending', max_length=20, verbose_name='renewal status'),
        ),
    ]
