# Generated by Django 5.0.9 on 2026-02-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0012_proforma_renewal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='proforma',
            name='approval_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('feedback', 'Feedback')], default='pending', max_length=20, null=True, verbose_name='approval status'),
        ),
        migrations.AlterField(
            model_name='processedorder',
            name='format',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('incoterm', 'Monthly (Incoterm)'), ('weekly', 'weekly'), ('10 days', '10 Days'), ('10 days_incoterm', '10 Days (incoterms)'), ('sez', 'SEZ'), ('sez_with_incoterm', 'SEZ (Incoterms)')], max_length=250, verbose_name='Format'),
        ),
    ]
